title: Noah Chans Portfolio
description: A portfolio page of Noah Chan from WHS, class of 2029.
URL: https://noah-2702.github.io/noahaidenchan.github.io/

remote_theme: poole/lanyon

#Sidebar
sidebar_links:
  Home: /
  About: /about/
  Projects: /projects/
