title: Noah Chans Portfolio
description: A portfolio page of Noah Chan from WHS, class of 2029.

url: "https://noah-2702.github.io"
baseurl: "/noahaidenchan.github.io"

remote_theme: poole/lanyon

#Sidebar
sidebar_links:
  Home: /
  Sports: /sports/
  Photo Portfolio: /photoportfolio/
